import type { Entity, Vector3Tuple } from "../contracts/world";
import { assetKitCatalog, catalogAssetDefinition } from "./assetKitCatalog";
import { designedFallbackDimensions } from "./designedFallback";

export type PrimitiveGeometry = "box" | "cylinder" | "sphere";

export interface AssetLod {
  /** Public URL for this browser-ready detail level. */
  modelUrl: string;
  /** Camera distance at which this level becomes active. LOD0 starts at zero. */
  minimumDistance: number;
}

export interface AssetDefinition {
  key: string;
  geometry: PrimitiveGeometry;
  dimensions: Vector3Tuple;
  color: string;
  /** Public URL for the preferred normalized glTF 2.0 binary asset. */
  modelUrl?: string;
  /** Near-to-far model variants generated by the offline optimization pipeline. */
  lods?: readonly AssetLod[];
  /** Public URL identifying an approved mesh package bundled into the runtime. */
  safeMeshUrl?: string;
  /** Public image projected onto controlled geometry for planar assets. */
  surfaceTextureUrl?: string;
  /** Normalized image crop in top-left coordinates: left, top, right, bottom. */
  surfaceCrop?: [number, number, number, number];
  /** Project-authored renderer used when a semantic object is better than a generic mesh. */
  proceduralModel?: "portrait" | "bay-window" | "silver-key" | "amber-pendant" | "canal" | "door";
  /** Actual stable support height measured from the asset's normalized bottom (0..1). */
  supportSurfaceY?: number;
  roughness?: number;
  metalness?: number;
}

export type AssetRegistry = Readonly<Record<string, AssetDefinition>>;

const fallback: AssetDefinition = {
  key: "fallback",
  geometry: "box",
  dimensions: [0.7, 0.7, 0.7],
  color: "#b8a995",
  roughness: 0.85,
};

export const defaultAssetRegistry: AssetRegistry = Object.fromEntries(
  assetKitCatalog.assets.map((asset) => [asset.registryKey, catalogAssetDefinition(asset)]),
);

export function resolveAsset(
  entity: Entity,
  registry: AssetRegistry = defaultAssetRegistry,
): AssetDefinition {
  const requested = entity.assetKey ?? entity.kind;
  const registered = registry[entity.id] ?? registry[requested];

  if (registered) {
    return entity.dimensions
      ? { ...registered, dimensions: entity.dimensions }
      : registered;
  }

  return {
    ...fallback,
    key: `fallback:${requested}`,
    dimensions: entity.dimensions ?? designedFallbackDimensions(entity),
  };
}
