/** Human-scale minimums shared by procedural city rendering and preflight. */
export const URBAN_HUMAN_SCALE = Object.freeze({
  minimumBuildingHeight: 7.2,
  doorHeight: 2.24,
  doorWidth: 0.98,
  windowSillHeight: 2.87,
  stallCounterHeight: 0.94,
  stallCanopyHeight: 2.42,
  balconyCenterProjection: 0.16,
  balconyDepth: 0.32,
  canalWaveAmplitude: 0.11,
  canalVolumeClearance: 0.018,
  canalWaterLevel: -0.31,
  canalBedTop: -0.58,
  canalCoverageRatio: 0.97,
  streetSurfaceTop: 0.068,
  sidewalkSurfaceTop: 0.19,
  facadeMaximumDepth: 3.96,
  horizonCenterFactor: 0.69,
  horizonApronDepthRatio: 0.5,
});
